// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace SGAS.Application.ViewModels
{
    public partial class EstadoViewModel
    {
       
        
        public int Id { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public int IdRegiao { get; set; }

        public virtual RegiaoViewModel Regiao { get; set; }
        
        public virtual ICollection<CidadeViewModel> Cidade { get; set; }
        
        public virtual ICollection<MesoRegiaoViewModel> MesoRegiao { get; set; }
    }
}