// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SGAS.Domain.Entity;
using System.Collections.Generic;

namespace SGAS.Application.ViewModels
{
    public partial class MesoRegiaoViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int IdEstado { get; set; }


        public virtual EstadoViewModel Estado { get; set; }

        public virtual ICollection<MicroRegiaoViewModel> MicroRegiao { get; set; }
    }
}