// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SGAS.Domain.Entity;
using System.Collections.Generic;

namespace SGAS.Application.ViewModels
{
    public partial class MicroRegiaoViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int IdMesoRegiao { get; set; }
        public virtual MesoRegiaoViewModel MesoRegiao { get; set; }
        public virtual ICollection<CidadeViewModel> Cidade { get; set; }
    }
}