// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using SGAS.Domain.Entity;
using System.Collections.Generic;

namespace SGAS.Application.ViewModels
{
    public partial class RegiaoViewModel
    {
        public int Id { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public virtual ICollection<EstadoViewModel> Estados { get; set; }
    }
}