// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public  class AspNetUserLogins //: IdentityUserLogin<int>
    {
        [Key]
        public string LoginProvider { get; set; }
        [Key]
        public string ProviderKey { get; set; }
        public string ProviderDisplayName { get; set; }
        public int UserId { get; set; }

        //[ForeignKey(nameof(UserId))]
        //[InverseProperty(nameof(AspNetUsers.AspNetUserLogins))]
        //public virtual AspNetUsers User { get; set; }
    }
}