// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class AspNetUserClaims : IdentityUserClaim<int>
    {
       // [Key]
        //public int Id { get; set; }
        //public int UserId { get; set; }
        //public string ClaimType { get; set; }
        //public string ClaimValue { get; set; }

        //[ForeignKey(nameof(UserId))]
        //[InverseProperty(nameof(AspNetUsers.AspNetUserClaims))]
        //public virtual AspNetUsers User { get; set; }
    }
}