// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class AspNetUserTokens : IdentityUserToken<int>
    {
        //[Key]
        //public int UserId { get; set; }
        //[Key]
        //public string LoginProvider { get; set; }
        //[Key]
        //public string Name { get; set; }
        //public string Value { get; set; }

        //[ForeignKey(nameof(UserId))]
        //[InverseProperty(nameof(AspNetUsers.AspNetUserTokens))]
        //public virtual AspNetUsers User { get; set; }
    }
}