// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public class AspNetUserRoles : IdentityUserRole<int>
    {
        //[Key]
        //public int UserId { get; set; }
        //[Key]
        //public int RoleId { get; set; }

        //[ForeignKey(nameof(RoleId))]
        //[InverseProperty(nameof(AspNetRoles.AspNetUserRoles))]
        public  FuncaoUsuario Role { get; set; }
        //[ForeignKey(nameof(UserId))]
        //[InverseProperty(nameof(AspNetUsers.AspNetUserRoles))]
        public  Usuario User { get; set; }

    }
}