// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class AspNetRoleClaims
    {
        [Key]
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }

        //[ForeignKey(nameof(RoleId))]
        //[InverseProperty(nameof(AspNetRoles.AspNetRoleClaims))]
        //public virtual AspNetRoles Role { get; set; }
    }
}