// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SGAS.Domain.Entity
{
    public class Cliente : EntidadeBase
    {
        public int Id { get; set; }

        public List<Agendamento> Agendamentos { get; set; }

        public List<Venda> Vendas { get; set; }

        public virtual Pessoa Pessoa { get; set; }

        public int IdPessoa { get; set; }

        public string CPF { get; set; }

        public string RG { get; set; }

        public string Nome { get; set; }

        public DateTime DataNascimento { get; set; }


    }
}