// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class Endereco : EntidadeBase
    {
        //[Key]
        public int Id { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
        public string Cep { get; set; }
       
        public int IdCidade { get; set; }
        
        public virtual Cidade Cidade { get; set; }

        //[ForeignKey(nameof(IdPessoa))]
        //[InverseProperty("Endereco")]
        public virtual Pessoa Pessoa { get; set; }

        public int IdPessoa { get; set; }

       

    }
}