// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class Estado : EntidadeBase
    {
        
        public int Id { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public int IdRegiao { get; set; }

        
        public virtual Regiao Regiao { get; set; }
        
         public virtual ICollection<Cidade> Cidade { get; set; }
        
        public virtual ICollection<MesoRegiao> MesoRegiao { get; set; }
    }
}