// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    
    public  class Funcao : EntidadeBaseRole
    {
        public override int Id { get; set; }

        [NotMapped]
        public virtual ICollection<FuncaoUsuario> FuncoesUsuarios { get; set; }

    }
}