// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public class ItemVenda : EntidadeBase
    {
        public int Id { get; set; }
        public int IdProduto { get; set; }
        public int Quantidade { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ValorUnitario { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ValorTotal { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Desconto { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime DataAtualizacao { get; set; }
        public int IdVenda { get; set; }

        public virtual Produto Produto { get; set; }
       
        public virtual Venda Venda { get; set; }
      
    }
}