// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class ItemReserva
    {
       
        public int Id { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime? DataFim { get; set; }
        public DateTime DataAtualizacao { get; set; }
        public int QuantidadeReservada { get; set; }
        public int QuantidadeDisponivel { get; set; }
        public int Saldo { get; set; }

        public virtual Produto Produto { get; set; }
        public int IdProduto { get; set; }

        public virtual ItemVenda ItemVenda { get; set; }

        public int IdReserva { get; set; }
       // public virtual Reserva Reserva { get; set; }
      
    }
}