// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class MesoRegiao : EntidadeBase
    {
       
        public int Id { get; set; }
        public string Nome { get; set; }
        public int? IdEstado { get; set; }

       
        public virtual Estado Uf { get; set; }
        
        public virtual ICollection<MicroRegiao> MicroRegiao { get; set; }
    }
}