// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public class Pessoa : EntidadeBase
    {


       // [Key]
        public int Id { get; set; }
        public bool EhEstrangeiro { get; set; }

        public string Observacao { get; set; }

        public DateTime DataCadastro { get; set; }
        public DateTime DataAlteracao { get; set; }
      
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }

       // [InverseProperty(nameof(SGAS.Domain.Entity.Endereco.Pessoa))]
        public virtual Endereco Endereco { get; set; }

        public int IdUsuario { get; set; }

        public virtual Usuario Usuario { get; set; }

       
        //[InverseProperty(nameof(SGAS.Domain.Entity.Funcionario.Pessoa))]
        public virtual Funcionario Funcionario { get; set; }

        public virtual Cliente Cliente { get; set; }

        public virtual Empresa Empresa { get; set; }

        public virtual Fornecedor Fornecedor { get; set; }

        public virtual UnidadeVenda UnidadeVenda { get; set; }
    }

}