// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public  class Produto : EntidadeBase
    {
       
        public int Id { get; set; }
        public string Descricao { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime DataAtualizacao { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Preco { get; set; }
        public bool? Ativo { get; set; }
        public int IdCategoria { get; set; }
      
        public virtual Categoria Categoria { get; set; }

        public virtual ICollection<ItemVenda> ItemVendas { get; set; }
    }
}