// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public partial class Reserva
    {
        public Reserva()
        {
            //ItemReserva = new HashSet<ItemReserva>();
        }

        [Key]
        public int Id { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime DataAtualização { get; set; }
        public string Status { get; set; }


        public int IdCliente { get; set; }
        public virtual Cliente Cliente { get; set; }

        public int? IdFuncionario { get; set; }
        public virtual Funcionario Funcionario { get; set; }


        public int? IdUnidadeVenda { get; set; }
        public virtual UnidadeVenda UnidadeVenda { get; set; }


        //public virtual ICollection<ItemReserva> ItemReserva { get; set; }
    }
}