// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestaoAgendamento.Domain.Entity
{
    public abstract class TipoPessoa
    {
        public TipoPessoa()
        {
            Pessoa = new HashSet<Pessoa>();
        }

        [Key]
        public int Id { get; set; }
        public string Descricao { get; set; }

        
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}