// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
   
    public class Usuario : EntidadeBaseUser
    {
        public override int Id { get; set; }
        public string Password { get; set; }
        public string Genero { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Nome { get; set; }

        [NotMapped]
        public virtual ICollection<FuncaoUsuario> FuncoesUsuarios { get; set; }
        public DateTime DataCriacao { get; set; }
        public DateTime DataAlteracao { get; set; }

        public virtual Pessoa Pessoa { get; set; }

        public virtual ICollection<Servico> ServicoCriacao { get; set; }

        public virtual ICollection<Servico> ServicoResponsavel { get; set; }


    }
}