// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SGAS.Domain.Entity
{
    public class Venda : EntidadeBase
    {
        
        public int Id { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public decimal Valor { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Desconto { get; set; }
        public int IdCliente { get; set; }
        public virtual Cliente Cliente { get; set; }
        public int? IdFuncionario { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public int? IdUnidadeVenda { get; set; }
        public virtual UnidadeVenda UnidadeVenda { get; set; }
        public virtual ICollection<ItemVenda> ItemVenda { get; set; }
    }
}